# Autogenerated wrapper script for Qt5QuickControls2_jll for x86_64-apple-darwin
export libqt5quickcontrols2, libqt5quicktemplates2, quickcontrols2

using Qt5Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt5QuickControls2")
JLLWrappers.@declare_library_product(libqt5quickcontrols2, "@rpath/QtQuickControls2")
JLLWrappers.@declare_library_product(libqt5quicktemplates2, "@rpath/QtQuickTemplates2")
JLLWrappers.@declare_file_product(quickcontrols2)
function __init__()
    JLLWrappers.@generate_init_header(Qt5Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt5quickcontrols2,
        "lib/QtQuickControls2.framework/Versions/5/QtQuickControls2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktemplates2,
        "lib/QtQuickTemplates2.framework/Versions/5/QtQuickTemplates2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        quickcontrols2,
        "qml/QtQuick/Controls.2",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
